git add .;
git commit -a -m "commit de para enviar para produção";
git push;
npm run build;
Copy-Item ".\dist" "..\temp" -Recurse -Force;
git switch build;
Remove-Item '.\assets';
Copy-Item "..\temp\dist\*" "." -Recurse -Force;
git add .;
git commit -a -m "Atualizado com a ultima versão dev";
git push;
